### ISSUE TITLE
v0.4.2 seems unstable - ethAdapter eventually fails with Error: Transaction has been reverted by the EVM

### ISSUE THREAD

**Issue by joaoluis-pdm** [PharmaLedger-IMI/blockchain-node-workspace#5]
The tests in fgt-dev https://github.com/PharmaLedger-IMI/fgt-workspace/releases/tag/v0.8.5 

ethAdapter fails periodically with  Error: Transaction has been reverted by the EVM:
```
Transaction Nonce  : 1248
Input for create or append smart contract :  2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkogWyLXtDDNVazUaP5CLTP9wjHskGVpHM2Yg3siX5zjJf2XgiYccasVnRr4SqEj5csu61Lgy1
UGtwp1cmUah3BA1kkvFeKufiYd6GaSzChSv73VMEZCnXPR5MY5D 4qnrBhooj78L2psbyjJ44LqFA4DA5xDn1EMWGF46ESUcFJe7Uh7FPKzWq5eXP4LrNfujPEPdqZddGFbG2mLZBFYCNDS6FCJ9L
hzq5MNLzg9erkEgsCsXgVrG7HJLp5gJgvqwSeTP9csEmrpDaYARh8eT5Jiyh7tKocVDSzyY7nYKCzJRoy4HYa9qLi9P2KwTmxXxqJKdRxzU1Uwqtmet1wqguPBTYQhkmphrJZapCF 1248
anchorID ssi:sza:traceability::BG/Ks5PUUEfZU1fmgxN7ibjrCqy/UMw8qor1XIABhKhjejs5WJiZvU2lgHPSljKieJCR4uEhidGH2roqDqk90Fk=:v0
anchorFactory methods {
  appendAnchor: [Function: bound _createTxObject],
  '0xc1c735b4': [Function: bound _createTxObject],
  'appendAnchor(string,string,uint8)': [Function: bound _createTxObject],
  createAnchor: [Function: bound _createTxObject],
  '0xa9fd4a2a': [Function: bound _createTxObject],
  'createAnchor(string,string,uint8)': [Function: bound _createTxObject],
  createOrUpdateMultipleAnchors: [Function: bound _createTxObject],
  '0x7e2ee190': [Function: bound _createTxObject],
  'createOrUpdateMultipleAnchors(string[])': [Function: bound _createTxObject],
  dumpAnchors: [Function: bound _createTxObject],
  '0x1f7ab91c': [Function: bound _createTxObject],
  'dumpAnchors(uint256,uint256,uint256)': [Function: bound _createTxObject],
  getAllVersions: [Function: bound _createTxObject],
  '0xd4dca96d': [Function: bound _createTxObject],
  'getAllVersions(string)': [Function: bound _createTxObject],
  getLastVersion: [Function: bound _createTxObject],
  '0x5436d6b2': [Function: bound _createTxObject],
  'getLastVersion(string)': [Function: bound _createTxObject],
  recover: [Function: bound _createTxObject],
  '0xd4a4871f': [Function: bound _createTxObject],
  'recover(bytes32,bytes,uint8)': [Function: bound _createTxObject],
  totalNumberOfAnchors: [Function: bound _createTxObject],
  '0x926a5c63': [Function: bound _createTxObject],
  'totalNumberOfAnchors()': [Function: bound _createTxObject]
}
finished get anchors : ssi:sza:traceability::BG/Ks5PUUEfZU1fmgxN7ibjrCqy/UMw8qor1XIABhKhjejs5WJiZvU2lgHPSljKieJCR4uEhidGH2roqDqk90Fk=:v0 [
  'ssi:shl:traceability:Gna4MzUwQuEXPwowdKVwRTwKXC5eHxQ77XZiQ655vjMK:1648565720555|QU36MyN0Oykw5tp1Cl0TFV/btaueMrGe0rGHAnF5yMPjjg813QqHL0aEw0pbxPPpnG0QMRvLQVlPouKa6IFWng==:v0',
  'ssi:shl:traceability:5uacpYLGNUMQfkYhcmdnZwRViCEMqwySGbnfTY33HehF:1648565729778|z+IUTr/LB9P2YZTPb8nJEQMCxoTWb1w8hqVLBV+x1kFRgKo8iMCCjmRe+PxXgRoFf58jWAKxVdgB+vXBB7bTnQ==:v0',
...
'ssi:shl:traceability:E76UZKKwzTuyXLnyvntubExHzkcZLbz6wQcLUppPE9LN:1648567088272|hkPGC2NX9rSVwzsMCGFuWfxywfzdpbHZF/6sFyGpnMTbGGvVFq8KqGDuhJC9FWRSyHoqhoWvgW+cbkyBPLz8LQ==:v0',
  'ssi:shl:traceability:4gnNMPLTHogs8C5aC8NEvVJAevGvk764WCWJPtWWhnaB:1648567090351|Rj79e8Od6ZJjlbLN/5AmBMRlUPDVpeXSxXhFp7WIm/R4ZVF67asutW7yippqxrpJrEPpFTnAT5/O8uonJdP1UQ==:v0',
  'ssi:shl:traceability:A94Y5YYsUctEEAVPjrJwEbN7aZpC7pD7zzC8Md8AV7co:1648567092436|EDbnmWIL50CMYoTvGy6zM0Hey8Ulz5S25cm/UQK/f7DJJ04IwJX+7Cc852YEr33yStARcOoKFPJtl+wVONj9sg==:v0',
  ... 68 more items
]
{
  anchorID: 'ssi:sza:traceability::BG/Ks5PUUEfZU1fmgxN7ibjrCqy/UMw8qor1XIABhKhjejs5WJiZvU2lgHPSljKieJCR4uEhidGH2roqDqk90Fk=:v0',
  newAnchorValue: 'ssi:shl:traceability:978jw19mjshkWPBfmyroQRLjYU2GhcCoAHgjewFqv9Lv:1648569131856|1U9a1dXFL/ZWt5DWFFP/cbUWiwohow1O5mfVv+Oa1bgh/Sc9uDE9BhKagtEiEU5xRUs8gMhd/m40X0SKEOl8DA==:v0',
  account: '0x7635d1693e7AB05944d35d591B58a9a93C0eA0ec'
}
Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0xea549af086187764fdcf38cd5a6b771c39c09b8028f030872f96c537cb4b07cd",
  "blockNumber": 4374,
  "contractAddress": null,
  "cumulativeGasUsed": 30000000,
  "from": "0x7635d1693e7ab05944d35d591b58a9a93c0ea0ec",
  "gasUsed": 30000000,
  "isPrivacyMarkerTransaction": false,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0x9bb22913aa0d731e9ed6ebe0a99793e4900dd080",
  "transactionHash": "0xcab4d9a5dc2d1de8d97d84a5e636159e67a9d7f61b72a49b61c94abc1783e498",
  "transactionIndex": 0,
  "events": {}
}
    at Object.TransactionError (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-helpers/lib/errors.js:87:21)
    at Object.TransactionRevertedWithoutReasonError (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-helpers/lib/errors.js:98:21)
    at /blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-method/lib/index.js:396:57
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  receipt: {
    blockHash: '0xea549af086187764fdcf38cd5a6b771c39c09b8028f030872f96c537cb4b07cd',
    blockNumber: 4374,
    contractAddress: null,
    cumulativeGasUsed: 30000000,
    from: '0x7635d1693e7ab05944d35d591b58a9a93c0ea0ec',
    gasUsed: 30000000,
    isPrivacyMarkerTransaction: false,
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    status: false,
    to: '0x9bb22913aa0d731e9ed6ebe0a99793e4900dd080',
    transactionHash: '0xcab4d9a5dc2d1de8d97d84a5e636159e67a9d7f61b72a49b61c94abc1783e498',
    transactionIndex: 0,
    events: {}
  }
}
```

Some code enters a loop repeating requests to the fgt-workspace api-hub:
```
172.16.63.64:8080 - [2022-03-29T16:51:42.412Z] GET:/anchor/traceability/get-last-version/2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkogWyLXtDDNVazUaP5CLTP9wjHskGVpHM2Yg3siX5zjJf2XgiYccasVnRr4SqEj5csu61Lgy1UGtwp1cmUah3BA1kkvFeKufiYd6GaSzChSv73VMEZCnXPR5MY5D 200 3.491ms
172.16.63.64:8080 - [2022-03-29T16:51:42.418Z] PUT:/bricking/traceability/put-brick 201 1.15ms
172.16.63.64:8080 - [2022-03-29T16:51:42.423Z] GET:/anchor/traceability/get-all-versions/2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkogWyLXtDDNVazUaP5CLTP9wjHskGVpHM2Yg3siX5zjJf2XgiYccasVnRr4SqEj5csu61Lgy1UGtwp1cmUah3BA1kkvFeKufiYd6GaSzChSv73VMEZCnXPR5MY5D 200 21.547ms
May or not be important, for safety check it! Failed to parse the error from the response due to SyntaxError: Unexpected token S in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/fgt-workspace/privatesky/psknode/bundles/pskWebServer.js:40672:42)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
172.16.63.64:8080 - [2022-03-29T16:51:42.449Z] PUT:/anchor/traceability/append-to-anchor/2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkogWyLXtDDNVazUaP5CLTP9wjHskGVpHM2Yg3siX5zjJf2XgiYccasVnRr4SqEj5csu61Lgy1UGtwp1cmUah3BA1kkvFeKufiYd6GaSzChSv73VMEZCnXPR5MY5D/4qnrBhooj78L2psbyjJ44LqFA4DA5z4qxfWeV4u8EKKqTHQuvDfrKuEGdAAQDfE8jdpTKrR9UtPsgqnjgbuZb7Va973vQCBYRtURTygg66PdTaAMPV6rWGfnVuhMYwFZ6j9uRmdg7nodbqtotRGJQGnzmjPbRQEi2k3somDRpAWGyyy5qreN4eXe5L2Aq1Exo4gCLFq3qoRqLa2dus5Wm9LXDBLVT88ESdm8e1eMHR 428 2,039.723ms
Request logs:
	Generic Error Middleware prevented message to be sent on response.write {"message":"Unable to add alias: versions out of sync"} undefined undefined172.16.63.64:8080 - [2022-03-29T16:51:44.491Z] GET:/anchor/traceability/get-last-version/2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkogWyLXtDDNVazUaP5CLTP9wjHskGVpHM2Yg3siX5zjJf2XgiYccasVnRr4SqEj5csu61Lgy1UGtwp1cmUah3BA1kkvFeKufiYd6GaSzChSv73VMEZCnXPR5MY5D 200 3.523ms
172.16.63.64:8080 - [2022-03-29T16:51:44.498Z] PUT:/bricking/traceability/put-brick 201 0.874ms
172.16.63.64:8080 - [2022-03-29T16:51:44.502Z] GET:/anchor/traceability/get-all-versions/2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkogWyLXtDDNVazUaP5CLTP9wjHskGVpHM2Yg3siX5zjJf2XgiYccasVnRr4SqEj5csu61Lgy1UGtwp1cmUah3BA1kkvFeKufiYd6GaSzChSv73VMEZCnXPR5MY5D 200 20.703ms
May or not be important, for safety check it! Failed to parse the error from the response due to SyntaxError: Unexpected token S in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/fgt-workspace/privatesky/psknode/bundles/pskWebServer.js:40672:42)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
172.16.63.64:8080 - [2022-03-29T16:51:44.528Z] PUT:/anchor/traceability/append-to-anchor/2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkogWyLXtDDNVazUaP5CLTP9wjHskGVpHM2Yg3siX5zjJf2XgiYccasVnRr4SqEj5csu61Lgy1UGtwp1cmUah3BA1kkvFeKufiYd6GaSzChSv73VMEZCnXPR5MY5D/4qnrBhooj78L2psbyjJ44LqFA4DA5yaw9hMWZRDvhPTph4crp9uu7YM5oKJFkpVwsFALGMfY77Asfom8UPmbaqv32QWmqzrZbw6yZHogHyzCeESN2pDnB1QWkaW9PrhxPNrFmMdm5AaNmvJHJVTSGhN1YGGQMYJHxDM5u6m8YxFyhatSiWaKMdRzuQXTmmR5Uht6Zw9HexLvAXFwnhqqytjRYXN8sxKpQ1e8cVBJwZ 428 2,041.216ms
Request logs:
	Generic Error Middleware prevented message to be sent on response.write {"message":"Unable to add alias: versions out of sync"} undefined undefined
```

**Comment by joaoluis-pdm** [comment]
This appears not to happen in an old ethadapter 62c61b4 (2021-Dec-17) that is up for +10 days now (same quorumengineering/quorum:21.7.1).
The use-case is different (and it is also using a very old psk-release db2b274 2021-Oct-15) - ctr-dev v0.11.5 2022-03-01 but possibly restarted 2022-03-21.

**Comment by joaoluis-pdm** [comment]
Up to https://github.com/PharmaLedger-IMI/fgt-workspace/commit/27ffc98ecde71cdaa03d8499d71ed17ccd014325 it was not possible to reproduce the problem on FGT...

Trying --istanbul.blockperiod 3 to see if it works as a workaround

**Comment by joaoluis-pdm** [comment]
--istanbul.blockperiod 3 gave exactly the same results.

**Comment by joaoluis-pdm** [comment]
```txt
[João Luís (PDM)] Finally a script that reproduces the problem... on any apihub installation with blockchain (at least for psk-release is e7c923d (2022-03-28), ethAdapter 1d40dbf (2022-03-29)):

https://github.com/PharmaLedger-IMI/fgt-workspace/blob/2fa68b75f043f84daae30e62b5874720a1ac94bb/tests/privateksy/createManyDSUs.js 

Adjustments needed to run:
 - needs the apihub setup on ../../apihub-root
 - line 4: edit the const domain = "traceability"
 - line 11: edit the require("../../privatesky/psknode/bundles/openDSU"); to adjust the path
 
 Description of behavious: It creates 1 "wallet DB DSU", and then loops forever 1) and 2):
  1) creates 4 "Product const DSUs" and then updates DB in the wallet DB
  2) creates a "Batch const DSU" + "BatchStatus DSU" , and then updates DB in the wallet DB
  
 The looping logic is +/- broken, but it finally reproduces the problem.
 
 On my laptop, the problem takes 127 creations of "Product const DSUs" for the problem to happens.
 With --istanbul.blockperiod 1 it takes +/- 20 minutes for the problem to start ocurring. (With --istanbul.blockperiod 3 I guess it would take least 3x more).
 
 On https://fgt-dev.pharmaledger.pdmfc.com/ is also took around 20min, and took also 127 creations of "Product const DSUs". 
 
 ???? 127 creations of "Product const DSUs" ???? (2^7-1 ????)
 
 It also runs on other domains. For example, I let it run on domain "ctr" (https://ctr-dev.pharmaledger.pdmfc.com/)
 (using ethadapter 62c61b4 (2021-Dec-17) psk-release db2b274 2021-Oct-15), and it did not broke for 45min (at least ... still running).
```

Being handled at https://github.com/PharmaLedger-IMI/epi-workspace/issues/670

**Comment by joaoluis-pdm** [comment]
Eventually, in CTR (using ethadapter 62c61b4 (2021-Dec-17) psk-release db2b274 2021-Oct-15), it also failed with:
```txt
    'ujtXcGiV2G', 'bzqIOvbPyD', 'gVsaecGjxw', 'PDkCbiaG7P', 'WfXIOAZ7WP',
    ... 49900 more items
  ]
}
>>> No observers found for event type change
(node:1088) UnhandledPromiseRejectionWarning: Error: WALLET_DB.commitBatch(hlStrings.slice is not a function)
    at ErrorWrapper (/ctr-workspace/ctr-patient/privatesky/psknode/bundles/openDSU.js:21403:22)
    at createOpenDSUErrorWrapper (/ctr-workspace/ctr-patient/privatesky/psknode/bundles/openDSU.js:21433:12)
    at /ctr-workspace/ctr-patient/tests/privatesky/createManyDSUs.js:128:76
    at /ctr-workspace/ctr-patient/privatesky/psknode/bundles/openDSU.js:1804:61
    at /ctr-workspace/ctr-patient/privatesky/psknode/bundles/openDSU.js:499:53
    at /ctr-workspace/ctr-patient/privatesky/psknode/bundles/openDSU.js:3372:53
    at /ctr-workspace/ctr-patient/privatesky/psknode/bundles/openDSU.js:5628:53
    at executeForSingleEntry (/ctr-workspace/ctr-patient/privatesky/psknode/bundles/openDSU.js:25238:51)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1088) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by joaoluis-pdm** [comment]
The test script at https://github.com/PharmaLedger-IMI/fgt-workspace/blob/2fa68b75f043f84daae30e62b5874720a1ac94bb/tests/privateksy/createManyDSUs.js 
works with simulated blockchain, but the apihub-root restarts with an error:

```txt
...
127.0.0.1:8080 - [2022-04-07T08:08:51.664Z] GET:/anchor/traceability/get-all-versions/2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkpLQft3Lr1sW7VwLDHvX7yscVkFF
qgcCnXywXpKc6bCwpC6KqwWQPpAwGGoQhLh6z6aPrNpx469KatxFTpBsfnyLiPc5HVGpcAGpxGgtAYfiK9Qu6rj3H8AHujN7 200 1,330.579ms
Parent process did not answer. Shutting down... [
  '/home/jpsl/.nvm/versions/node/v14.17.4/bin/node',
  '/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bin/scripts/pskApiHubLauncher.js'
] false
ESC[33mExit caught on spawned file /export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bin/scripts/pskApiHubLauncher.js ESC[0
m
Process will restart in 100 ms ...
[ServiceLauncher] Starting a new process using </export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bin/scripts/pskApiHubLauncher.js>
[ServiceLauncher] Process with PID=[33299] was spawned.
...
127.0.0.1:8080 - [2022-04-07T08:28:50.899Z] GET:/anchor/traceability/get-all-versions/2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkpLQft3Lr1sW7VwLDHvX7yscVkFFqgcCnXywXpKc6bCwpC6KqwWQPpAwGGoQhLh6z6aPrNpx469KatxFTpBsfnyLiPc5HVGpcAGpxGgtAYfiK9Qu6rj3H8AHujN7 200 1,818.233ms
Parent process did not answer. Shutting down... [
  '/home/jpsl/.nvm/versions/node/v14.17.4/bin/node',
  '/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bin/scripts/pskApiHubLauncher.js'
] false
Exit caught on spawned file /export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bin/scripts/pskApiHubLauncher.js 
Process will restart in 200 ms ...
[ServiceLauncher] Starting a new process using </export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bin/scripts/pskApiHubLauncher.js>
[ServiceLauncher] Process with PID=[49175] was spawned.
```

The client eventually blows up with:
```txt
[POST] http://localhost:8080/anchor/traceability/append-to-anchor/2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkpLQft3Lr1sW7VwLDHvX7yscVkFFqgcCnXywXpKc6bCwpC6KqwWQPpAwGGoQhLh6z6aPrNpx469KatxFTpBsfnyLiPc5HVGpcAGpxGgtAYfiK9Qu6rj3H8AHujN7/4qnrBhooj78L2psbyjJ44LqFA4DA5yqV4DfzbqksmbvvPJ7yc25YWX4pjAHiAQkNojVDmtPa6jYE1NGtRxjC8Uyo4Er6o4e1xuCH33TSMwn13HUgeNNKnsrKDVcdSXmtEwLTCzTEJR76NwediKNmkn5YKdR5i95QeCfxkNEKxrgtpG5FsYdjT31hux1e17DgfmQof9nkEzFUpCij4NKzQbVg7AVt7P3PhdQJRjsT6w Error: socket hang up
    at connResetException (internal/errors.js:628:14)
    at Socket.socketOnEnd (_http_client.js:499:23)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ECONNRESET'
}
qui 07 abr 2022 09:28:53 WEST
```
(The timestamp above is WEST, while the apihub-root timestamps seems in UTC).

The average number of "Product DSUs" created is much higher than the "fixed 127" with blockchain enabled.

```txt
jpsl@PDM-00781:/export/home/jpsl/develop/PharmaLedger/fgt-workspace/tests/privateksy$ grep "Product DSU created with" createManyDSUs_NOBC15.log | wc -
   1702   10212  171902 -
jpsl@PDM-00781:/export/home/jpsl/develop/PharmaLedger/fgt-workspace/tests/privateksy$ grep "Product DSU created with" createManyDSUs_NOBC.log | wc -
    551    3306   55651 -
```

**Comment by joaoluis-pdm** [comment]
Problem remains the same with eth-adapter v1.0.3

Reverting change.

**Comment by joaoluis-pdm** [comment]
On OpenDSU acceleration meeting 2022-09-13, it was presented that this problem seems due to some sort of GoQuorum limitation/protection.
2 kinds of workaround will be provided:
1 - OBA (Optimistic Blockchain Anchoring)
2 - throttling at the eth-adapter (client will have do deal with errors and retry...)

**Comment by joaoluis-pdm** [comment]
Have to commit octopus-freeze.json so the ethadapater can be upgraded from ee6b2a4 to 6642225 (1.0.5)
