### ISSUE TITLE
v0.4.6 ethadapter v1.0.5 concurrency issue

### ISSUE THREAD

**Issue by joaoluis-pdm** [PharmaLedger-IMI/blockchain-node-workspace#8]
In the scope of https://github.com/PharmaLedger-IMI/blockchain-node-workspace/issues/5#issuecomment-1245393626 , where fgt-workspace upgraded to psk-release be8027202d04032bed93fb8de74253d61ec6a3b9, and ethadapter from ee6b2a4 to 6642225 (v1.0.5)

If we build a single wallet, we find no trouble.

If we build multiple wallets, we get (on the fgt-workspace side):

```txt
...
seed KeySSI created with SSI 2vkohTn1jVeB8ZSr4vJvNcP3WjGNLWK9nwKvj7sm3qzY7VkDBjcR1qtKPu
Caught an error during JSON.parse Error
May or not be important, for safety check it! Failed to parse the error from the response due to SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:26218:42)
    at IncomingMessage.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
The wallet couldn't be created. Trying to load with credentials...
Environment for vault dashboard no-cache
Loading wallet with ssi 3XXka29Q8KUGeWVtxRkGGtuNtSmT7jJd28mZCpB9VemEqC6JQ1ymrXAiV1sXvpfDa5a1rd9Dp4tjk3XwKDJfqiUejW6PnNMF3tpGpT9
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Could not load wallet DSU Error: Failed to get the list of hashlinks(Unexpected end of JSON input)".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

Full set of logs: https://homes.pdmfc.com/jpsl/PharmaLedger/fgtEth20221017/

(There are more MAHs, which do not have the logs shown here. Here we only track the failure of building one MAH, but fgt-workspace.log has all concurrent "traceability" apihub events)

mah-msd.log fails at 2022-10-17T10:49:37.961894699Z with ""Could not load wallet DSU Error: Failed to get the list of hashlinks(Unexpected end of JSON input)""

fgt-workspace.log at that time shows:
```txt
2022-10-17T10:49:35.964207970Z INFO     0x00 1666003775964 Logger      apihub/logg 172.16.63.62:8080 - [2022-10-17T10:49:35.962Z] GET:/anchor/traceability/get-last-version/29fgyfS13tr4gjabfTYGXNFDRPzLXrRDajXxGZEZ14bN2DEkQjHGhqxxkkfHu9HQXdxA3ju1F2hWdzF75BaVffiAKW8Zw5Z 200 1.871ms
2022-10-17T10:49:35.980271020Z ERROR    0x00 1666003775969 Eth         apihub/anch {
2022-10-17T10:49:35.980309836Z   error: Error: Request Failed.
2022-10-17T10:49:35.980317894Z   Status Code: 429
2022-10-17T10:49:35.980338361Z   URL: 172.16.16.16:3000/createAnchor/29fgyfS13tr4gjabfTYGXNFDRPzLXrRDajXxGZEZ14bN2DEkQjHGhqxxkkfHu9HQXdxA3ju1F2hWdzF75BaVffiAKW8Zw5Z/G73iPJYaFmfMiBcFYy1vLzEqPxiV3hGaStCihXbBcuSkfV5Pf9aQWvuocoBWW7mRVu8QVooX2cBrvAMeevRorCXhPkgxf
2022-10-17T10:49:35.980343555Z       at ClientRequest.<anonymous> (/fgt-workspace/privatesky/psknode/bundles/pskWebServer.js:44282:13)
2022-10-17T10:49:35.980352585Z       at Object.onceWrapper (node:events:646:26)
2022-10-17T10:49:35.980359146Z       at ClientRequest.emit (node:events:526:28)
2022-10-17T10:49:35.980364306Z       at HTTPParser.parserOnIncomingClient (node:_http_client:618:27)
2022-10-17T10:49:35.980369735Z       at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
2022-10-17T10:49:35.980374269Z       at Socket.socketOnData (node:_http_client:482:22)
2022-10-17T10:49:35.980378951Z       at Socket.emit (node:events:526:28)
2022-10-17T10:49:35.980384101Z       at addChunk (node:internal/streams/readable:315:12)
2022-10-17T10:49:35.980389287Z       at readableAddChunk (node:internal/streams/readable:289:9)
2022-10-17T10:49:35.980393820Z       at Socket.Readable.push (node:internal/streams/readable:228:10)
2022-10-17T10:49:35.980399085Z       at TCP.onStreamRead (node:internal/stream_base_commons:190:23),
2022-10-17T10:49:35.980409567Z   statusCode: 429,
2022-10-17T10:49:35.980415491Z   message: ''
2022-10-17T10:49:35.980421329Z }
```

ethadapter.log shows no errors whatsoever

**Comment by joaoluis-pdm** [comment]
I think we have not understood the propose of the throttler in the new ethadapter v1.0.5...

We tryed a simpler test: https://homes.pdmfc.com/jpsl/PharmaLedger/createManyDSUs20221018/

Running a single script "createManyDSUs.js" script (which should be the base of  https://github.com/PharmaLedger-IMI/epi-workspace/issues/670 - source at https://github.com/PharmaLedger-IMI/fgt-workspace/blob/master/tests/privateksy/createManyDSUs.js),
with a single apihub (runServer.log),
and a single ethadapter (ethadapter.log).

The apihub (runServer.log) reports
```txt
...
ERROR    0x00 1666097530505 Eth         apihub/anch {
  error: Error: Request Failed.
  Status Code: 429
  URL: 172.16.16.16:3000/appendAnchor/2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkpUzaH5oZz1WRbwEsvHGDZ22bqU5K334JKnsRSiAFstVWBjNxS7R5Z8gvG3Bsv6KiLWCqeohemzBNPLW6yEUNKs4p8kJRbBUpLdYsquRcyhGbBLfdznesu89EQY7/4qnrBhooj78L2psbyjJ44LqFA4DA5x8PnUfQn2bSLdAgzwDoFtaPZ24L3DtWYzgd7eXWsZ7nBExKK3ZpwJMGhq6Xqz1FUfVSE7tMY4RzTYVCAUxhF52BfVGidTKvpMtJbtEvBiFzVTcEUKeRZYZzzXtXmUDBZ9Gdp9V1Km7Dp4K895Q9wuSAGKMxgZ5zF7irTTwJoU5yuatLaBSvTSdpaSFKEf6Qj9hEUfMQt76apX
      at ClientRequest.<anonymous> (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/pskWebServer.js:44282:13)
      at Object.onceWrapper (node:events:646:26)
      at ClientRequest.emit (node:events:526:28)
      at HTTPParser.parserOnIncomingClient (node:_http_client:618:27)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
      at Socket.socketOnData (node:_http_client:482:22)
      at Socket.emit (node:events:526:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23),
  statusCode: 429,
  message: ''
}
```

The ethadapter.log reports nothing unusual.


The createManyDSUs.log reports

```txt
Caught an error during JSON.parse Error
May or not be important, for safety check it! Failed to parse the error from the response due to SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:26218:42)
    at IncomingMessage.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:25584
            newErr = new Error(message + `(${err.originalMessage})`);
                     ^

Error: WALLET_DB.commitBatch(Error)
    at ErrorWrapper (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:25584:22)
    at createOpenDSUErrorWrapper (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:25614:12)
    at /export/home/jpsl/develop/PharmaLedger/fgt-workspace/tests/privateksy/createManyDSUs.js:128:76
    at /export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:2205:57
    at endAnchoring (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:3739:9)
    at updateAnchorCallback (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:4303:36)
    at executeForSingleEntry (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:30691:51)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  originalMessage: 'Error',
  previousError: Error: Failed to anchor(Error)
      at ErrorWrapper (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:25584:22)
      at createOpenDSUErrorWrapper (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:25614:12)
      at /export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:2205:58
      at endAnchoring (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:3739:9)
      at updateAnchorCallback (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:4303:36)
      at executeForSingleEntry (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:30691:51)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    originalMessage: 'Error',
    previousError: Error: Error
        at ErrorWrapper (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:25587:22)
        at createOpenDSUErrorWrapper (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:25614:12)
        at executeForSingleEntry (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:30691:52)
        at processTicksAndRejections (node:internal/process/task_queues:96:5) {
      originalMessage: 'Error',
      previousError: { statusCode: 500, message: 'Error' },
      debug_message: 'Failed to execute entryError: Failed during execution of append-to-anchor',
      type: -2
    },
    debug_message: 'Failed to anchor',
    debug_stack: 'Error: Error\n' +
      '    at ErrorWrapper (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:25587:22)\n' +
      '    at createOpenDSUErrorWrapper (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:25614:12)\n' +
      '    at executeForSingleEntry (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:30691:52)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
  },
  debug_message: 'WALLET_DB.commitBatch',
  debug_stack: 'Error: Failed to anchor(Error)\n' +
    '    at ErrorWrapper (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:25584:22)\n' +
    '    at createOpenDSUErrorWrapper (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:25614:12)\n' +
    '    at /export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:2205:58\n' +
    '    at endAnchoring (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:3739:9)\n' +
    '    at updateAnchorCallback (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:4303:36)\n' +
    '    at executeForSingleEntry (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/privatesky/psknode/bundles/openDSU.js:30691:51)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}
```

**Comment by joaoluis-pdm** [comment]
> PS: And I disagree from

> >  if you check the errors objects are wrapped and enriched with context and call traces

> (At the current version) I don't seem to be able to interpret "Error: Failed to anchor(Error)" as a "Please retry" indication...
